# Generated by Django 3.1.2 on 2020-11-18 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateTimeField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.IntegerField()),
                ('date', models.DateField(help_text='Enter the date of infecious')),
                ('category', models.CharField(choices=[('Local', 'Local'), ('Imported', 'Imported')], max_length=32)),
                ('virus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virus.virus')),
            ],
        ),
    ]
