# Generated by Django 3.1.2 on 2020-11-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virus',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
    ]
