# Generated by Django 3.1.2 on 2020-11-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0002_auto_20201118_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virus',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
