# Generated by Django 3.1.2 on 2020-11-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avtar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
