# Generated by Django 3.1.2 on 2020-11-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201119_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='avtar',
            new_name='avatar',
        ),
    ]
