# Generated by Django 3.1.2 on 2020-11-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201119_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='department',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
