# Generated by Django 3.1.2 on 2020-11-18 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('XCoordinate', models.IntegerField()),
                ('YCoordinate', models.IntegerField()),
                ('DateFrom', models.DateField()),
                ('DateTo', models.DateField()),
                ('category', models.CharField(choices=[('Visit', 'Visit'), ('Residence', 'Residence'), ('Workplace', 'Workplace')], max_length=32)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.patientvisit')),
            ],
        ),
    ]
