# Generated by Django 3.1.2 on 2020-11-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_visitlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlocation',
            name='is_from_api',
            field=models.IntegerField(default=0),
        ),
    ]
