# Generated by Django 3.1.2 on 2020-11-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_visitlocation_is_from_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitlocation',
            name='is_from_api',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
