# Generated by Django 3.1.2 on 2020-11-19 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0004_auto_20201119_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('is_from_api', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='visitlocation',
            old_name='DateFrom',
            new_name='date_from',
        ),
        migrations.RenameField(
            model_name='visitlocation',
            old_name='DateTo',
            new_name='date_to',
        ),
        migrations.RemoveField(
            model_name='visitlocation',
            name='XCoordinate',
        ),
        migrations.RemoveField(
            model_name='visitlocation',
            name='YCoordinate',
        ),
        migrations.RemoveField(
            model_name='visitlocation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='visitlocation',
            name='is_from_api',
        ),
        migrations.AlterField(
            model_name='visitlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.location'),
        ),
    ]
