# Generated by Django 3.1.2 on 2020-11-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_auto_20201119_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
