# Generated by Django 3.1.2 on 2020-11-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0006_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
