# Generated by Django 3.1.2 on 2020-11-08 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotZone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Case',
        ),
        migrations.RemoveField(
            model_name='virus',
            name='Case',
        ),
        migrations.AddField(
            model_name='case',
            name='Patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HotZone.patient'),
        ),
        migrations.AddField(
            model_name='case',
            name='Virus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HotZone.virus'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HotZone.patient')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='Visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HotZone.visit'),
        ),
    ]
