# Generated by Django 3.1.2 on 2020-11-12 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotZone', '0002_auto_20201108_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='Patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='Case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HotZone.case'),
        ),
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
