# Generated by Django 3.1.2 on 2020-10-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotZone', '0003_virus_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='DateFrom',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='DateTo',
            field=models.DateTimeField(blank=True, max_length=100, null=True),
        ),
    ]
